export * from './CartPage'
export * from './MainPage'
export * from './OrderType'
export * from './MenuPage'
export * from './CategoryPage'
export * from './FormInRestaurantPage'
export * from './FormTakeAwayPage'